//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallLogging
    {
        public int CallId { get; set; }
        public string CustomerCode { get; set; }
        public string System { get; set; }
        public string CallDetails { get; set; }
        public string CallReportedBy { get; set; }
        public string CallLogDate { get; set; }
        public string CallLogTime { get; set; }
        public string CallAttendedBy { get; set; }
        public string CallAttendedDate { get; set; }
        public string CallAttendedTime { get; set; }
        public string CallClosedBy { get; set; }
        public string CallClosedDate { get; set; }
        public string CallClosedTime { get; set; }
        public string EngineerRemarks { get; set; }
        public string CustomerRemarks { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
        public string PaymentType { get; set; }
        public string QR { get; set; }
    }
}
