//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public int Id { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string ContactPersonName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
        public string CustomerType { get; set; }
        public string InstallationDate { get; set; }
        public string ExpiryDate { get; set; }
    }
}
