//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationMaster
    {
        public int Id { get; set; }
        public string SiteSetupCode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string SiteCode { get; set; }
        public string SiteName { get; set; }
        public string Contact { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
    }
}
