//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrincipalMaster
    {
        public int PricipalID { get; set; }
        public string PrincipalCode { get; set; }
        public string PrincipalName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string Contact { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
    }
}
