//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSetupProductDetail
    {
        public int Id { get; set; }
        public string SiteSetupCode { get; set; }
        public Nullable<int> SNo { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string ProductCode { get; set; }
        public string VersionCode { get; set; }
        public Nullable<int> Qty { get; set; }
        public string InstallationDate { get; set; }
        public string ExpiryDate { get; set; }
        public string Remarks { get; set; }
        public string CustomerType { get; set; }
    }
}
