//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusMaster
    {
        public int Id { get; set; }
        public string StatusCode { get; set; }
        public string Status { get; set; }
    }
}
